# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e041c59f8b27b79b9c49d138365ca8aa69d457a4344edc20f173d849e3deb70c0f5621df90b4d654569e6e87e85fd4c1bdcd1b37acadde24fd08e93285fa41b

test:
  secret_key_base: 5b3d1ed9090c31bda2cfbade7cda486b401366c581210e14f8ce29229e2a891d7f706d63931399b4aeca6cbe3301df05da00a5fb93386743268b7f844fbdb725

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
